services:
  api:
    # Ahora usamos la imagen desde Docker Hub
    image: 330440573974.dkr.ecr.us-east-1.amazonaws.com/mini-proyecto-backend:latest
    container_name: gestion_tareas_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Database=Server=mini-proyecto-cloud-db.cezggmqg2ryj.us-east-1.rds.amazonaws.com,1433;Initial Catalog=gestionTareasDB;User ID=AdminTarea;Password=junior03;TrustServerCertificate=True;MultipleActiveResultSets=True;
    ports:
      - "80:8080"
    restart: unless-stopped
    logging:
      driver: "awslogs"
      options:
        awslogs-group: "backend-net-app-logs"
        awslogs-region: "us-east-1"
        awslogs-stream-prefix: "gestion-tareas"